/*
* Generated file
*
* Generated from: yang module name: kitchen-service-impl yang module local name: kitchen-service-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Thu Jan 14 16:46:02 EST 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.kitchen_service.impl;
public class KitchenServiceModuleFactory extends org.opendaylight.controller.config.yang.config.kitchen_service.impl.AbstractKitchenServiceModuleFactory {

}
